[package]
name = "octopus"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6.1.0"
ndarray = "0.16.1"
num-traits = "0.2.19"
parking_lot = "0.12.4"
rand = "0.9.1"
rand_distr = "0.5.1"
rayon = "1.10.0"
thiserror = "2.0.12"
